source = ./configs/env.conf
source = ./configs/misc.conf
source = ./configs/input.conf
source = ./configs/binds.conf
source = ./configs/layouts.conf
source = ./configs/rules.conf
source = ./configs/appearance.conf
source = ./configs/animations.conf
source = ./configs/autostart.conf
