# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 12.0

cursor_trail 1
cursor_trail_start_threshold 0

scrollback_lines 2000

window_resize_step_cells 0
window_resize_step_lines 0
window_padding_width 0 10

resize_in_steps no
confirm_os_window_close 0

tab_bar_style powerline

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
