# Window effect
blur = 0
blur_layer = 0
blur_optimized = 1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

shadows = 1
layer_shadows = 0
shadow_only_floating = 1
shadows_size = 12
shadows_blur = 12
shadows_position_x = -12
shadows_position_y = -12
shadowscolor = 0x00000080

border_radius = 12
no_radius_when_single = 0
focused_opacity = 1.0
unfocused_opacity = 1.0

# Appearance
gappih = 5
gappiv = 5
gappoh = 5
gappov = 5
overviewgappi = 5
overviewgappo = 20

scratchpad_width_ratio = 0.8
scratchpad_height_ratio = 0.9
borderpx = 1

rootcolor           = 0x1e1e2eff
bordercolor         = 0x1e1e2eff
dropcolor           = 0x45475a20
splitcolor          = 0xeba0acFF
focuscolor          = 0x45475aff
maximizescreencolor = 0xa6e3a1ff
urgentcolor         = 0xf38ba8ff
scratchpadcolor     = 0x89b4faff
globalcolor         = 0xcba6f7ff
overlaycolor        = 0xfab387ff

# Overview Jump Mode
jump_label_decorate_fg_color = 0xcdd6f4ff
jump_label_decorate_bg_color = 0x1e1e2eff
jump_label_decorate_focus_fg_color = 0xf5e0dcff
jump_label_decorate_focus_bg_color = 0x313244ff
jump_label_decorate_border_color = 0x313244ff
jump_label_decorate_border_width = 1
jump_label_decorate_corner_radius = 12
jump_label_decorate_padding_x = 5
jump_label_decorate_padding_y = 5
jump_label_decorate_font_desc = Rubik Bold 16

# Monocle Layout Tab Bar
group_bar_height = 50
group_bar_decorate_fg_color = 0xcdd6f4ff
group_bar_decorate_bg_color = 0x1e1e2eff
group_bar_decorate_focus_fg_color = 0xf5e0dcff
group_bar_decorate_focus_bg_color = 0x313244ff
group_bar_decorate_border_color = 0x313244ff
group_bar_decorate_border_width = 1
group_bar_decorate_corner_radius = 12
group_bar_decorate_padding_x = 5
group_bar_decorate_padding_y = 5
group_bar_decorate_font_desc = Rubik Bold 10

# Cursor
cursor_size=24
cursor_theme=catppuccin-mocha-light-cursors
