# Auto start
exec-once=systemctl --user start mango-session.target
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=awww-daemon
exec-once=foot --server
exec-once=waybar
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=hyprctl setcursor 'Catppuccin Mocha Light' 24

exec=mb-reload
