# layout support:
tagrule = id:1,layout_name:scroller
tagrule = id:2,layout_name:scroller
tagrule = id:3,layout_name:scroller
tagrule = id:4,layout_name:scroller
tagrule = id:5,layout_name:scroller
tagrule = id:6,layout_name:scroller
tagrule = id:7,layout_name:scroller
tagrule = id:8,layout_name:scroller
tagrule = id:9,layout_name:scroller

# layer rule
layerrule = animation_type_open:zoom,layer_name:rofi
layerrule = animation_type_close:zoom,layer_name:rofi

layerrule = noanim:1,noblur:1,layer_name:selection
layerrule = noanim:1,noblur:1,layer_name:wayfreeze
layerrule = noanim:1,noblur:1,layer_name:awww-daemon

# Window rules
windowrule = ignore_maximize:1,ignore_minimize:1,appid:^(.*)$
windowrule = isterm:1,appid:^(footclient|foot)$

windowrule = tags:1,appid:^(?i)brave(.*)$
windowrule = tags:1,appid:^(?i)chromium(.*)$
windowrule = tags:1,appid:^(?i)firefox(.*)$
windowrule = tags:3,appid:^(?i)dev.zed.Zed$
windowrule = tags:5,appid:^(?i)obsidian$
windowrule = tags:5,appid:^(?i)discord$
windowrule = tags:5,appid:^(?i)vesktop$
windowrule = tags:5,appid:^(?i)spotify$
windowrule = tags:5,appid:^(?i)(.*)youtube_music$

windowrule = isfloating:1,appid:^(?i)xdg-desktop-portal-gtk$
windowrule = isfloating:1,appid:^(?i)brave(.*)$,title:^(?i)_crx_(.*)$
windowrule = isfloating:1,width:1024,height:538,appid:^footclient$,title:^ft$

windowrule = isfloating:1,isglobal:1,isoverlay:1,width:683,height:384,title:^(?i)\bpicture[ _-]?in[ _-]?picture\b$
