source = $HOME/.config/hypr/themes/mocha.conf

$accent = $pink
$accentAlpha = $pinkAlpha
$font = CaskaydiaCove Nerd Font

# GENERAL
general {
  hide_cursor = false
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.cache/wallpaper
  blur_passes = 2
  color = $base
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = $overlay0
  font_size = 12
  font_family = $font
  position = 20, 20
  halign = left
  valign = bottom
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 80
  font_family = $font
  position = -20, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 15
  font_family = $font
  position = -28, -120
  halign = right
  valign = top
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 130
  border_color = $accent
  rounding = 0
  border_size = 2
  position = 0, 55
  halign = center
  valign = center
}

# USER NAME
label {
  monitor =
  text = Welcome back, Nutt
  color = $text
  font_size = 15
  font_family = $font
  position = 0, -30
  halign = center
  valign = center
}

# Now Playing
label {
  monitor =
  text = cmd[update:1000] echo "Now Playing: $(playerctl metadata artist) - $(playerctl metadata title)"
  color = $overlay0
  font_size = 12
  font_family = $font
  position = -20, 20
  halign = right
  valign = bottom
}

# INPUT FIELD
input-field {
  monitor =
  size = 250, 40
  outline_thickness = 2
  rounding = 0
  dots_size = 0.3
  dots_spacing = 0.4
  dots_center = true
  dots_rounding = 0
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = true
  placeholder_text = <span foreground="##$textAlpha">󰌾 Logged in as <span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, 40
  halign = center
  valign = bottom
}
