hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm app -- awww-daemon")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("systemctl --user start vicinae")
  hl.exec_cmd("hyprctl setcursor 'Catppuccin Mocha Light' 24")
end)
